name: Market Scheduler (run live_intraday every minute during market hours)

on:
  schedule:
    # run every minute between 03:00-10:59 UTC Mon-Fri (we will check market hours inside the script)
    - cron: "*/1 3-10 * * 1-5"
  workflow_dispatch: {}  # manual trigger

permissions:
  contents: write  # needed to push state/trades back using GITHUB_TOKEN

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run single iteration of bot
        run: python live_intraday.py --once

      - name: Commit state and trades (if changed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --verbose live_state.json || true
          git add --verbose live_paper_trades.csv || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update live bot state/trades [$GITHUB_RUN_ID]" || true
            git push origin HEAD:${{ github.ref_name }}
          fi
